
module.exports = {
"ivr-account_number" : "Account number"
,"ivr-connect_to_caller" : "Connect to caller"
,"ivr-enter_ext_pound" : "If you know your party's extension, please enter it now"
,"ivr-enter_ext" : "Please enter an extension followed by the pound sign"
,"ivr-for_this_person" : "For this person"
,"ivr-hold_connect_call" : "Please hold while I connect your call"
,"ivr-im_sorry" : "I'm sorry"
,"ivr-please" : "Please"
,"ivr-please_return_our_call_at" : "Please return our call at"
,"ivr-regarding_reference_number" : "Regarding reference number"
,"ivr-sample_submenu" : "This is a sample IVR submenu..."
,"ivr-say_name" : "Please say your name after the tone"
,"ivr-send_to_voicemail" : "Send this caller to voicemail"
,"ivr-speak_to_a_customer_service_representative" : "To speak to a customer service representative"
,"ivr-take_a_message" : "Take a message"
,"ivr-that_was_an_invalid_entry" : "That was an invalid entry"
,"ivr-this_is_a_call_from" : "This is a call from"
,"ivr-this_ivr_will_let_you_test_features" : "This IVR will let you test some of the features..."
,"ivr-to_call_the_freeswitch_conference" : "To call the FreeSWITCH conference"
,"ivr-to_do_a_freeswitch_echo_test" : "To do a FreeSWITCH echo test"
,"ivr-to_do_a_fwd_echo_test" : "To do a fwd echo test"
,"ivr-to_hear_sample_submenu" : "To hear a sample IVR submenu"
,"ivr-to_hear_screaming_monkeys" : "To hear screaming monkeys"
,"ivr-to_listen_to_moh" : "To listen to music on hold"
,"ivr-to_repeat_these_options" : "To repeat these options"
,"ivr-to_return_to_previous_menu" : "To return to the previous menu"
,"ivr-to_speak_with_an_operator" : "To speak with an operator"
,"ivr-welcome_to_freeswitch" : "Welcome to FreeSWITCH, the future of telephony"
,"ivr-you_may_exit_by_hanging_up" : "You may exit at any time by simply hanging up"
,"ivr-or" : "or"
,"ivr-not" : "not"
,"ivr-call" : "call"
,"ivr-you_may" : "You may"
,"ivr-hello" : "hello"
,"ivr-use_telephone_keypad" : "Using your telephone keypad..."
,"ivr-spell_name" : "Please spell the name of the person you are trying to reach."
,"ivr-last_name_first" : "Last name first"
,"ivr-first_name_first" : "First name first"
,"ivr-press_one_q_or_z" : "Press 1 for Q or Z."
,"ivr-sales" : "Sales"
,"ivr-customer_service" : "Customer service"
,"ivr-technical_support" : "Technical support"
,"ivr-operator" : "Operator"
,"ivr-you_have_dialed_an_invalid_extension" : "You have dialed an invalid extension."
,"ivr-please_enter_extension_followed_by_pound" : "Please enter your extension, followed by the pound sign."
,"ivr-please_enter_pin_followed_by_pound" : "Please enter your pin number, followed by the pound sign."
,"ivr-pin_or_extension_is-invalid" : "Your pin number or extension is invalid."
,"ivr-you_are_about_to_provision_this_phone" : "You are about to provision this phone to your account..."
,"ivr-please_reenter_your_pin" : "Please re-enter your pin number to confirm."
,"ivr-register_for_cluecon" : "To register for ClueCon, please press..."
,"ivr-to_log_in" : "to log in"
,"ivr-to_log_out" : "to log out"
,"ivr-you_are_now_logged_in" : "You are now logged in"
,"ivr-you_are_now_logged_out" : "You are now logged out"
,"ivr-please_try_again" : "Please try again."
,"ivr-provision_phone_permanently_to_extension" : "You are about to provision this phone permanently to your extension."
,"ivr-extension_to_provision_this_phone":"Please enter the extension number to which you would like to provision this phone, followed by the pound sign."
,"ivr-this_phone_will_now_reboot" : "Thank you, this phone will now reboot."
,"ivr-recording_saved" : "Thank you. Your recording has been saved."
,"ivr-save_review_record" : "Press 1 to save your recording. Press 2 to review your recording. Press 3 to re-record."
,"ivr-unable_save" : "The system is unable to save your sound file at this time. Please try again later."
,"ivr-you_are_number" : "You are number..."
,"ivr-in_line" : "...in line"
,"ivr-thank_you_for_holding" : "Thank you for holding."
,"ivr-estimated_hold_time" : "Your estimated hold time is..."
,"ivr-more_than" : "More than..."
,"ivr-less_than" : "Less than..."
,"ivr-begin_recording" : "Begin recording."
,"ivr-call_forwarding_has_been_cancelled" : "Call forwarding has been cancelled."
,"ivr-call_forwarding_has_been_set" : "Call forwarding has been set."
,"ivr-please_enter_the_phone_number" : "Please enter the phone number."
,"ivr-please_state_your_name_and_reason_for_calling" : "Please state your name and the reason for your call."
,"ivr-accept_reject_voicemail" : "To accept, press 1. To reject, press 2. To send to voicemail, press 3."
,"ivr-accept_reject" : "To accept, press 1. To reject, press 2."
,"ivr-to_accept_press_one" : "To accept, press 1."
,"ivr-incoming_call" : "Incoming call."
,"ivr-thank_you_for_calling" : "Thank you for calling."
,"ivr-stay_on_line_call_answered_momentarily" : "Please stay on the line. Your call will be answered momentarily."
,"ivr-call_being_transferred" : "Your call is being transferred."
,"ivr-enjoy_music_while_transfer" : "Please enjoy the music while your call is being transferred."
,"ivr-call_from" : "You have a call from..."
,"ivr-no_menu_items" : "This menu has no items. Please contact the administrator."
,"ivr-for_directory_press" : "For a directory, press..."
,"ivr-using_telephone_keypad" : "Using your telephone keypad..."
,"ivr-enter_letters_last_name" : "Enter the first few letters of the person's last name."
,"ivr-enter_letters_first_name" : "Enter the first few letters of the person's first name."
,"ivr-enter_letters_first_or_last_name" : "Enter the first few letters of the person's first or last name."
,"ivr-if_correct_press" : "If this is correct, press..."
,"ivr-if_not_press" : "If not, press..."
,"ivr-finished_pound_hash_key" : "When you are finished, press the pound or hash key."
,"ivr-dnd_activated" : "Do not disturb is now activated."
,"ivr-dnd_cancelled" : "Do not disturb has been cancelled."
,"ivr-any_other_digit" : "Press any other digit..."
,"ivr-one_yes_two_no" : "Press one for yes. Press two for no."
,"ivr-enter_queue_number" : "Please enter the queue number, followed by the pound or hash sign."
,"ivr-please_enter_the" : "Please enter the..."
,"ivr-number" : "Number."
,"ivr-followed_by_pound" : "...followed by the pound or hash key."
,"ivr-account_balance_is" : "The account balance is..."
,"ivr-file" : "...file..."
,"ivr-files" : "...files..."
,"ivr-for_a_wakeup_call" : "For a wakeup call..."
,"ivr-this_is_your_wakeup_call" : "This is your wakeup call."
,"ivr-request_wakeup_call" : "To request a wakeup call..."
,"ivr-confirm_wakeup_call" : "To confirm a wakeup call..."
,"ivr-cancel_wakeup_call" : "To cancel a wakeup call..."
,"ivr-requested_wakeup_call_for" : "You have requested a wakeup call for..."
,"ivr-not_requested_wakeup_call" : "You have not requested a wakeup call."
,"ivr-wakeup_call_cancelled" : "Your wakeup call has been cancelled."
,"ivr-for_daily_wakeup_call" : "For a daily wakeup call..."
,"ivr-daily_wakeup_call" : "Daily wakeup call..."
,"ivr-for_daily_wakeup_calls" : "For daily wakeup calls..."
,"ivr-for_one_time_wakeup_call" : "For a one-time wakeup call..."
,"ivr-one_time_wakeup_call" : "One-time wakeup call..."
,"ivr-wakeup_call" : "...wakeup call..."
,"ivr-wakey_wakey_sunshine" : "Wakey wakey sunshine!"
,"ivr-welcome" : "Welcome."
,"ivr-welcome_to" : "Welcome to..."
,"ivr-good_morning" : "Good morning."
,"ivr-good_afternoon" : "Good afternoon."
,"ivr-good_evening" : "Good evening."
,"ivr-thank_you" : "Thank you."
,"ivr-for" : "For..."
,"ivr-longer_than_usual_hold_times" : "We are experiencing longer than usual hold times."
,"ivr-you_are_the" : "You are the..."
,"ivr-one_moment_please" : "One moment please."
,"ivr-call_answered_order_received" : "Your call will be answered in the order it was received."
,"ivr-you_entered" : "You entered..."
,"ivr-extension_number" : "Extension number..."
,"ivr-please_hold_while_party_contacted" : "Please hold while your party is being contacted."
,"ivr-please_enjoy_music_while_party_reached" : "Please enjoy the music while your party is being reached."
,"ivr-generic_greeting" : "Thank you for calling. If you know your party's extension, please enter it now, or dial nine for a directory."
,"ivr-if_correct_one_if_not_two" : "If this is correct, press 1. If not, press 2."
,"ivr-repeat_this_information" : "To repeat this information..."
,"ivr-no_no_no" : "No no no!"
,"ivr-did_you_mean_to_press_key" : "Did you mean to press that key?"
,"ivr-seriously_mean_to_press_key" : "Seriously. Did you REALLY mean to press that key?"
,"ivr-oh_whatever" : "Oh what-EVER."
,"ivr-one_more_mistake" : "That's it! One more mistake and I WILL hang up on your ass."
,"ivr-congratulations_you_pressed_star": "Congratulations, you pressed star. This does not mean you ARE a star. It simply means that you can press buttons and probably have fingers."
,"ivr-engineers_busy_assisting_other_sales": "All of our engineers are busy assisting other sales guys with demonstrating how cool the CudaTel is."
,"ivr-message_self_destruct" : "This message will self-destruct in 5, 4, 3, 2, 1..."
,"ivr-all_your_call_are_belong_to_us" : "All your call are belong to us."
,"ivr-love_those_touch_tones" : "I just love the way you press those touch tones!"
,"ivr-yes_we_have_no_bananas" : "Yes, we have no bananas."
,"ivr-dude_you_suck" : "Dude, you suck!"
,"ivr-on_hold_indefinitely" : "Your call is very important to us, but your sanity is not, so we will be happy to keep you on hold, forever torturing you with our annoying hold music."
,"ivr-has_left_the_building" : "...has left the building."
,"ivr-phone_is_unassigned" : "This phone is unassigned and may not be used to make external calls."
,"ivr-phone_not_configured" : "This phone is not configured properly."
,"ivr-phone_is_configured_properly" : "Congratulations! This phone is configured properly and may now be assigned to a user."
,"ivr-contact_system_administrator" : "Please contact the system administrator for assistance."
,"ivr-no_calls_waiting_in_queue" : "There are no calls waiting in this queue."
,"ivr-you_are_number_one" : "You are caller number one. Of course, *every* caller is number one in our book so you may be waiting a while."
,"ivr-has_called_emergency_services" : "...has called emergency services"
,"ivr-there_are" : "There are..."
,"ivr-enter_source_telephone_number" : "Please enter the source telephone number, then press pound."
,"ivr-enter_destination_telephone_number" : "Please enter the destination telephone number, then press pound."
,"ivr-recording_started" : "Recording started."
,"ivr-recording_stopped" : "Recording stopped."
,"ivr-recording_paused" : "Recording paused."
,"ivr-recording_deleted" : "Recording deleted."
,"ivr-no_longer_in_queue" : "You are no longer in queue."
,"ivr-withdrawn" : "...withdrawn."
,"ivr-question" : "question..."
,"ivr-questions" : "...questions."
,"ivr-has_been_answered" : "...has been answered."
,"ivr-has_been_removed" : "...has been removed."
,"ivr-no_questions_in_queue" : "No questions in queue."
,"ivr-is_now_on" : "...is now on."
,"ivr-is_now_off" : "...is now off."
,"ivr-phone_not_make_external_calls" : "This phone is not allowed to make external calls."
,"ivr-id_number" : "I.D. number..."
,"ivr-skip_instructions" : "To skip these instructions..."
,"ivr-hangup_to_discard" : "Hang up the call without pressing a key to discard the recording."
,"ivr-or_press" : "...or press..."
,"ivr-for_english_press" : "For English, press..."
,"ivr-call_cannot_be_completed_as_dialed" : "Your call cannot be completed as dialed."
,"ivr-please_check_number_try_again" : "Please check the number and try again."
,"ivr-failure_reason_is" : "Failure reason is..."
,"ivr-unallocated_number" : "Unallocated number"
,"ivr-no_user_response" : "No user response"
,"ivr-invalid_number_format" : "Invalid number format"
,"ivr-invalid_sound_prompt" : "Invalid sound prompt."
,"ivr-gateway_down" : "Gateway down"
,"ivr-no_route_destination" : "No route to destination"
,"ivr-user_busy" : "User busy"
,"ivr-call_rejected" : "Call rejected"
,"ivr-normal_unspecified" : "Normal unspecified"
,"ivr-incompatible_destination" : "Incompatible destination"
,"ivr-normal_clearing" : "Normal clearing"
,"ivr-not_have_permission" : "You do not have permission to perform this action."
,"ivr-youre_doing_it_wrong" : "You're doing it wrong, but I'll try to connect you anyway. (Douchebag!)"
,"ivr-were_asterisk_free" : "3... 2... 1... WE'RE ASTERISK FREE!!!"
,"ivr-douche_telecom" : "Thank you for calling Douche Telecom, where we make sure that your communications never have that 'not so fresh' feeling!"
,"ivr-to_learn_more_about_freeswitch" : "To learn more about FreeSWITCH..."
,"ivr-there_is" : "There is..."
,"ivr-do_not_call_list" : "That number is on the Do Not Call list."
,"ivr-call_attempt_aborted" : "The call attempt has been aborted."
,"ivr-to_wait_stay_on_the_line" : "To wait for the next available representative, please stay on the line."
,"ivr-if_you_would_like_us_to_call_back" : "If you would like us to call you back, press..."
,"ivr-it_appears_that_your_phone_number_is" : "It appears that your phone number is..."
,"ivr-would_you_like_to_receive_a_call_at_this_number" : "Would you like to receive a call at this number?"
,"ivr-please_enter_the_number_where_we_can_reach_you" : "Please enter the number where we can reach you."
,"ivr-we_will_return_your_call_at_this_number" : "We will return your call at this number as soon as possible."
,"ivr-anonymous_caller" : "Anonymous caller."
,"ivr-freeguipy" : "Have your self a slice of free gooey pie!"
,"ivr-learn_more_freeguipydotorg" : "Learn more at F-R-E-E-G-U-I-P-Y dot O-R-G"
,"ivr-terribly_wrong_awkward" : "Something went terribly, terribly wrong... (awkward!)"
,"ivr-it_was_that_bug" : "Well I'll be a monkey's bitch! It *was* that bug!"
,"ivr-concentrate" : "CONCENTRATE! Focus on the bunny! FOCUS ON THE BUNNY!"
,"ivr-file_a_jira" : "If you dont like it, you can file a JIRA!"
,"ivr-founder_of_freesource" : "Allow me to introduce, the founder of FreeSOURCE, Anthony Ministrone."
,"ivr-cold_foolish" : "Man, that is cold foolish...COLD Foolish"
,"ivr-trollover_minutes" : "Congratulations! You've earned 1500 Trollover minutes this month!"
,"ivr-yuno_silent_drill" : "Y U NO Silent Drill?!"
,"ivr-beacuase" : "Beacuase, the voices where pretty good"
,"ivr-day_mode" : "Day mode..."
,"ivr-night_mode" : "Night mode..."
,"ivr-lunch_mode" : "Lunch mode..."
,"ivr-custom_mode_number" : "Custom mode number..."
,"ivr-not_have_permission_to_edit" : "You do not have permission to edit..."
,"ivr-this_feature" : "This feature."
,"ivr-feature" : "Feature."
,"ivr-automated_attendants" : "Automated attendants."
,"ivr-automated_attendant" : "Automated attendant."
,"ivr-please_enter_extension_number_of" : "Please enter the extension number of the..."
,"ivr-that_you_would_like_to_modify" : "...that you would like to modify."
,"ivr-invalid_extension_try_again" : "Invalid extension - please try again."
,"ivr-modify_main_prompts" : "To modify main prompts..."
,"ivr-modify_option_prompts" : "To modify option prompts..."
,"ivr-hear_usage_stats" : "To hear usage statistics..."
,"ivr-at_the_tone" : "At the tone..."
,"ivr-record_prompt" : "Please record the prompt."
,"ivr-record_short_greeting" : "Please record the short greeting."
,"ivr-record_invalid_sound" : "Please record the invalid sound prompt."
,"ivr-record_exit_sound" : "Please record the exit sound prompt."
,"ivr-when_finished_press_any_key" : "When finished, press any key."
,"ivr-press_key_of_prompt_to_modify" : "Press the key of the prompt you would like to modify."
,"ivr-key" : "Key..."
,"ivr-does_not_contain_a_recording" : "...does not contain a recording."
,"ivr-already_contains_a_recording" : "...already contains a recording."
,"ivr-option" : "Option..."
,"ivr-has_had" : "...has had..."
,"ivr-visitors" : "...visitors."
,"ivr-visitor" : "...visitor."
,"ivr-reset_usage_totals" : "To reset usage totals..."
,"ivr-reset_usage_totals_confirm" : "You have chosen to reset usage totals."
,"ivr-to_confirm" : "...to confirm."
,"ivr-usage_totals_have_been_reset" : "Usage totals have been reset to zero."
,"ivr-to_modify" : "To modify..."
,"ivr-to_modify_main_prompt" : "To modify main prompt..."
,"ivr-short_greeting" : "...the short greeting."
,"ivr-ivalid_sound_prompt" : "...the invalid sound prompt."
,"ivr-exit_sound_prompt" : "...the exit sound prompt."
,"ivr-not_accept_anonymous_calls" : "That person does not accept anonymous calls."
,"ivr-to_accept_press" : "To accept, press..."
,"ivr-to_reject" : "To reject..."
,"ivr-hang_up" : "...hang up."
,"ivr-to_reject_hangup" : "To reject, hang up the call without pressing a key."
,"ivr-access_denied" : "Access denied."
,"ivr-perform_dtmf_test" : "To perform a DTMF test, press..."
,"ivr-perform_echo_test" : "To perform an echo test, press..."
,"ivr-perform_delayed_echo_test" : "To perform a delayed echo test, press..."
,"ivr-hangup_to_end_test" : "Hang up to end the test."
,"ivr-read_each_key_press_back" : "Press one or more keys. I will read each key press back to you."
,"ivr-echo_your_audio_back" : "After the tone, I will echo your audio back to you."
,"ivr-delayed_echo_your_audio_back" : "After the tone, I will send a delayed echo of your audio back to you."
,"ivr-send_fax" : "To send a fax, press..."
,"ivr-enter_number_send_fax" : "Please enter the number to which I should send this fax, then press pound."
,"ivr-send_fax_now" : "Send your fax now."
,"ivr-has_been_added_to_the_blacklist" : "...has been added to the blacklist."
,"ivr-has_been_removed_from_blacklist" : "...has been removed from the blacklist."
,"ivr-enter_number_to_add_to_blacklist" : "Please enter the number to be added to the blacklist."
,"ivr-enter_number_to_remove_from_blacklist" : "Please enter the number to remove from the blacklist"
,"ivr-is_not_on_the_blacklist" : "...is not on the blacklist."
,"ivr-is_already_on_the_blacklist" : "...is already on the blacklist."
,"ivr-for_other_options" : "For other options, press..."
,"ivr-your_caller_id_information_is" : "Your caller I.D. information is..."
,"ivr-call_screening_enabled" : "Call screening has been enabled."
,"ivr-call_screening_disabled" : "Call screening has been disabled."
,"ivr-prompt" : "Prompt."
,"ivr-enabled" : "...enabled."
,"ivr-disabled" : "...disabled."
,"ivr-aint_nobody_got_time_for_that" : "Ain't nobody got time for that!"
,"ivr-we_would_support" : "We would support the shit out of you if only you returned our phone calls and emails."
,"ivr-suck" : "...suck."
,"ivr-sucks" : "...sucks."
,"ivr-to_redial_last_call" : "To redial your last call..."
,"ivr-ensure_service_keeps_working" : "To ensure that your service keeps working..."
,"ivr-please_contact" : "Please contact..."
,"ivr-the_billing_department" : "...the billing department..."
,"ivr-by_dialing" : "...by dialing..."
,"ivr-credit_card_could_not_be_charged" : "The credit card on file could not be charged."
,"ivr-units" : "...units..."
,"ivr-per_minute" : "...per minute."
,"ivr-your_caller_id_number_is_blocked" : "Your caller ID number is blocked."
,"ivr-unblock_caller_id" : "You must unblock your caller ID for PIN-less authorization to the calling card."
,"ivr-request_or_use_pin" : "Alternatively, you can request or use a PIN code on your account."
,"ivr-you_have_used" : "You have used..."
,"ivr-out_of" : "...out of..."
,"ivr-next_billing_cycle" : "Your next billing cycle begins on..."
,"ivr-nothing" : "Nothing."
,"ivr-to_skip" : "To skip..."
,"ivr_connect_live_operator" : "Please hold while we connect you to a live operator."
,"ivr-connect_actual_human_being" : "Please hold while we connect you to an actual *human being*."
,"ivr-system_down_for_maintenance" : "The system is going down for maintenance."
,"ivr-system_back_up_in_approximately" : "The system will be back up in approximately..."
,"ivr-you_lose": "It's all there, black and white, clear as crystal! You stole fizzy lifting drinks! You bumped into the ceiling which now has to be washed and sterilized, so you get nothing! You lose! Good day, sir!"
,"ivr-cold_pop" : "To grab a cold pop, press..."
,"ivr-barbecuing" : "If you thought someone was barbecuing, press..."
,"ivr-no_shoes" : "If you didn't grab no shoes or nothing and ran for your life, press..."
,"ivr-smoke_got_you" : "If the smoke got you, press..."
,"ivr-got_bronchitis" : "If you got bronchitis, press..."
,"ivr-nobody_got_time_for_that" : "If ain't nobody got time for that, press..."
,"ivr-reminder_for" : "This is a reminder for..."
,"ivr-appointment_schedule_for" : "You have an appointment scheduled for..."
,"ivr-Your_verification_PIN_is" : "Your verification PIN is..."
,"ivr-hotseat_intro" : "To hear the hotseat menu, please enter your extension followed by the pound or hash key."
,"ivr-modify_main_prompt" : "To modify main prompt..."
,"ivr-hotseat_pin" : "Please enter your pin number followed by the pound or hash key."
,"ivr-hotseat_options" : "To hotseat this phone to your extension, press 1. To remove hotseat on this phone, press 2."
,"ivr-maximum_number_of_channels" : "You have reached the maximum number of channels."
,"ivr-to_do_a_echo_test" : "To do an echo test"
}